#!/bin/bash

set -e

verbose() {
    echo $ "$@"
    "$@"
}


if test -z "$1"

# Initial call
then
    while
        RESULTS="$(gfind . -type d -name 'bower_components' -print0 -quit)"
        echo -n "$RESULTS" | xargs -0 -n1 "$0"
        test -n "$RESULTS"
    do
        :
    done

# Recursive call
else
    BOWER_COMPONENTS_DIR="$1"
    PROJ_ROOT="$(dirname "$BOWER_COMPONENTS_DIR")"

    echo
    verbose cd "$PROJ_ROOT"

    verbose env GZIP=-9 tar -czf bower_components.tar.gz -- bower_components
    verbose trash -a bower_components
fi
