#!/bin/bash

set -e

verbose() {
    echo $ "$@"
    "$@"
}


if test -z "$1"

# Initial call
then
    while
        RESULTS="$(gfind . -type d -name '*.pg' -print0 -quit)"
        echo -n "$RESULTS" | xargs -0 -n1 "$0"
        test -n "$RESULTS"
    do
        :
    done

# Recursive call
else
    PG_DIR="$1"
    PROJ_ROOT="$(dirname "$PG_DIR")"
    PG_DIR_BASENAME="$(basename "$PG_DIR")"

    echo
    verbose cd "$PROJ_ROOT"

    verbose env GZIP=-9 tar -czf "$PG_DIR_BASENAME".tar.gz -- "$PG_DIR_BASENAME"
    verbose trash -a "$PG_DIR_BASENAME"
fi
