#!/bin/bash

set -e

verbose() {
    echo $ "$@"
    "$@"
}


if test -z "$1"

# Initial call
then
    while
        RESULTS="$(gfind . -type d -name 'node_modules' -print0 -quit)"
        echo -n "$RESULTS" | xargs -0 -n1 "$0"
        test -n "$RESULTS"
    do
        :
    done

# Recursive call
else
    NODE_MODULES_DIR="$1"
    PROJ_ROOT="$(dirname "$NODE_MODULES_DIR")"

    echo
    verbose cd "$PROJ_ROOT"

    verbose env GZIP=-9 tar -czf node_modules.tar.gz -- node_modules
    verbose trash -a node_modules
fi
