printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
trailingComma: all
arrowParens: always

overrides:
  # Add trailing comma to JSON, as described here:
  # https://github.com/prettier/prettier/issues/5708#issuecomment-491610261
  - files:
      - "*.json"
      - "*.sublime-settings"
    options:
      parser: json5
      printWidth: 0
      quoteProps: "preserve"
      singleQuote: false
      trailingComma: all
