printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
trailingComma: all
arrowParens: always

overrides:
  # TODO: wait for resolution here https://github.com/prettier/prettier/issues/5708
  - files: "*.json"
    options:
      trailingComma: all
