#!/usr/bin/env bash


if [ "$1" == start ]; then
	launchctl load ~/'Library/LaunchAgents/com.interestinglythere.actively.plist'
	echo "Logging started."
elif [ "$1" == stop ]; then
	launchctl unload ~/'Library/LaunchAgents/com.interestinglythere.actively.plist'
	echo "Logging stopped."
else
	echo "usage: `basename $0` start | stop" # | kill"
fi
