tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "szhu/personal"
brew "deno"
brew "fish"
brew "gh"
brew "node"
brew "iconsur"
brew "jhead"
brew "mas"
brew "micro"
brew "mupdf"
brew "openjdk@11"
brew "poppler"
brew "ripgrep"
brew "shellcheck"
brew "swiftformat"
brew "terminal-notifier"
brew "trash"
cask "apple-hewlett-packard-printer-drivers"
cask "autodesk-fusion360"
cask "avibrazil-rdm"
cask "betterdisplay"
cask "bluesnooze"
cask "descript"
cask "discord"
cask "font-sf-pro"
cask "fontforge"
cask "gitup"
cask "google-chrome"
cask "google-drive"
cask "grandperspective"
cask "inkscape"
cask "league-of-legends"
cask "loom"
cask "maccy"
cask "middleclick"
cask "monitorcontrol"
cask "mos"
cask "notunes"
cask "obsidian"
cask "paparazzi"
cask "qlmarkdown"
cask "shortcat"
cask "sloth"
cask "spotify"
cask "visual-studio-code"
cask "zoom"
cask "zoomin"
cask "zotero"
mas "AdBlock", id: 1402042596
mas "Display Menu", id: 549083868
mas "Hand Mirror", id: 1502839586
mas "HexColor", id: 446103121
mas "Hidden Bar", id: 1452453066
mas "Keynote", id: 409183694
mas "Messenger", id: 1480068668
mas "Next Meeting", id: 1017470484
mas "Numbers", id: 409203825
mas "One Thing", id: 1604176982
mas "Pages", id: 409201541
mas "Playgrounds", id: 1496833156
mas "Post-it®", id: 1475777828
mas "Redirect Web for Safari", id: 1571283503
mas "Slack", id: 803453959
mas "Userscripts", id: 1463298887
mas "Velja", id: 1607635845
